#!name=番茄小说 @zqzess
#!desc=番茄小说广告屏蔽, version = 3.0

[Rule]
DOMAIN-SUFFIX,pangolin-sdk-toutiao.com,REJECT
DOMAIN-SUFFIX,zijieapi.com,REJECT
DOMAIN-SUFFIX,frontier-toutiao.snssdk.com,REJECT
DOMAIN-SUFFIX,pangolin-sdk-toutiao-b.com,REJECT
DOMAIN-SUFFIX,ads5-normal-lf.zijieapi.com,REJECT
DOMAIN-SUFFIX,pglstatp-toutiao.com,REJECT
DOMAIN-SUFFIX,api3-normal-lf.fqnovel.com,REJECT
DOMAIN-SUFFIX,dig.bdurl.net,REJECT
DOMAIN-SUFFIX,frontier-toutiao.snssdk.com,REJECT
DOMAIN-SUFFIX,log5-applog-lf.fqnovel.com,REJECT
DOMAIN-SUFFIX,dig.bdurl.net,REJECT
DOMAIN-SUFFIX,security.snssdk.com,REJECT
DOMAIN-SUFFIX,mon11-misc-lf.fqnovel.com,REJECT
DOMAIN-SUFFIX,ads3-normal-lf.zijieapi.com,REJECT
DOMAIN-SUFFIX,p9-ad-sign.byteimg.com,REJECT
DOMAIN-SUFFIX,ads3-normal-lf.zijieapi.com,REJECT
DOMAIN-SUFFIX,ads5-normal-lf.zijieapi.com,REJECT
DOMAIN-SUFFIX,p6-ad-sign.byteimg.com,REJECT
